version: 2.1
orbs:
   aws-cli: circleci/aws-cli@4.0.0
   serverless: circleci/serverless-framework@2.0.1
jobs:
   deploy:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
        # run Install
       - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
       - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity
       # run deploy
       - run: serverless deploy --verbose
workflows:
  app_deploy:
    jobs:
      - deploy:
          context:
            - "serverless-context"