version: 2.1
orbs:
   aws-cli: circleci/aws-cli@4.0.0
   serverless: circleci/serverless-framework@2.0.1
jobs:
   deploy:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
        # run Install
       - run: 
           name: sls plugin install
           command: serverless plugin install -n serverless-webpack
       # run deploy
       - run: serverless deploy --verbose
workflows:
  app_deploy:
    jobs:
      - deploy